SPRING_MAIL_HOST: ${ENV_SPRING_MAIL_HOST}
spring:
  application:
    name: cardstore
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: America/Sao_Paulo
    default-property-inclusion: non_null
  jpa:
    hibernate:
      ddl-auto: update
  docker:
    compose:
      file: "./compose.yaml"

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer



server:
  port: 8081

  